version: "3"

services:
#SUBSISTEMA 1 
 backend-clientes:
    image: stoplight/prism:4
    container_name: SIS_1-clientes_server
    command: mock --cors -h 0.0.0.0 "/aos/clientes.yaml"
    ports:
      - 4012:4010
    volumes:
      - ./otherServices/subsistema_1:/aos:ro
    networks:
        - gestor_talleres
 frontend-clientes:
    image: swaggerapi/swagger-ui
    container_name: SIS_1-clientes_front
    ports:
      - 8001:8080
    environment:
      SWAGGER_JSON: /aos/clientes.yaml
    volumes:
      - ./otherServices/subsistema_1:/aos:ro
    networks:
        - gestor_talleres

#SUBSISTEMA 2
 backend-vehiculos:
    image: stoplight/prism:4
    container_name: SIS_2-vehiculos_server
    command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
    ports:
      - 4013:4010
    volumes:
      - ./otherServices/subsistema_2:/aos:ro
    networks:
        - gestor_talleres
 frontend-vehiculos:
    image: swaggerapi/swagger-ui
    container_name: SIS_2-vehiculos_front
    ports:
      - 8002:8080
    environment:
      SWAGGER_JSON: /aos/openapi.yaml
    volumes:
      - ./otherServices/subsistema_2:/aos:ro
    networks:
        - gestor_talleres

#SUBSISTEMA 3
 backend-trabajos:
    image: stoplight/prism:4
    container_name: SIS_3-trabajos_server
    command: mock --cors -h 0.0.0.0 "/aos/swagger.yaml"
    ports:
      - 4011:4010
    volumes:
      - ./otherServices/subsistema_3:/aos:ro
    networks:
        - gestor_talleres
 frontend-trabajos:
    image: swaggerapi/swagger-ui
    container_name: SIS_3-trabajos_front
    ports:
      - 8003:8080
    environment:
      SWAGGER_JSON: /aos/swagger.yaml
    volumes:
      - ./otherServices/subsistema_3:/aos:ro
    networks:
        - gestor_talleres

#SUBSISTEMA 4
 backend-notificaciones:
    image: stoplight/prism:4
    container_name: SIS_4-notificaciones_server
    command: mock --cors -h 0.0.0.0 "/aos/swagger.yaml"
    ports:
      - 4014:4010
    volumes:
      - ./otherServices/subsistema_4:/aos:ro
    networks:
        - gestor_talleres
 frontend-notificaciones:
    image: swaggerapi/swagger-ui
    container_name: SIS_4-notificaciones_front
    ports:
      - 8004:8080
    environment:
      SWAGGER_JSON: /aos/swagger.yaml
    volumes:
      - ./otherServices/subsistema_4:/aos:ro
    networks:
        - gestor_talleres

#SUBSISTEMA 5
 backend-facturas:
    image: mwan93/aos_servicio_facturas:v0.2
    container_name: SIS_4-facturas_server
    ports:
      - 4010:4010
    networks:
        - gestor_talleres
 frontend-facturas:
    image: swaggerapi/swagger-ui
    container_name: SIS_4-facturas_front
    ports:
      - 8005:8080
    environment:
      SWAGGER_JSON: /aos/openapi.yaml
    volumes:
      - ./openapi:/aos:ro
    networks:
        - gestor_talleres

#SUBSISTEMA 6
 servicio-recambios:
    image: ghcr.io/adrianja5/aos-implementacion-servicio-recambios:latest
    container_name: SIS_6-recambios
    ports:
      - 8006:8080
    networks:
        - gestor_talleres

#SUBSISTEMA 7
 backend-logs:
    image: stoplight/prism:4
    container_name: SIS_7-logs_server
    command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
    ports:
      - 8007:4010
    volumes:
      - ./otherServices/subsistema_7:/aos:ro
    networks:
        - gestor_talleres

networks:
    gestor_talleres:
